### ISSUE TITLE
Don't respond to comments which provide a direct link

### ISSUE THREAD

**Issue by jameswolff96** [Theonefoster/DirectImageLinkerBot#1]
Taken from [here](https://www.reddit.com/r/anime_irl/comments/4jt7yk/anime_irl/d39z76o?context=1)

```
[From one of the top posts here from this month](http://imgur.com/FVHNkmh)

From this post: https://www.reddit.com/r/anime_irl/comments/4j95w1/anime_irl/
```

In this case a direct link was provided (the first one) for the post (the second link) which I am assuming triggered the bot.

**Comment by AcesFullOfKings** [comment]
Thanks for the feedback. Did you read the links under my comment? Maybe that will explain your confusion.

**Comment by jameswolff96** [comment]
Ah fair play, I am actually on mobile and the app I use hasn't resolved imgur links like this in the past, it must be from a recent update (or I am just extremely stupid...both very likely).

However, do you have code in place to keep a situation like what I thought I had from happening? Might be something to consider.

Sorry to bother!
