### ISSUE TITLE
Can fake ban from subreddit

### ISSUE THREAD

**Issue by GreenBeard** [Theonefoster/DirectImageLinkerBot#2]
Send the bot a private message with a ban title. Example "You've been banned from participating in /r/mildlyinteresting" as the title bans it from mildlyinteresting. I tried it before I posted this bug and it worked :(. Please remove /r/mildlyinteresting from the banned list.

**Comment by AcesFullOfKings** [comment]
Thanks, I've added a fix and just need to test it. In fixing this issue I've discovered that my database is 100GB which is clearly not good so I'll need to add something to keep it clean. I suspect that data["doneSubmissions"] is getting too big as it has a week's worth of reddit data (just the ID's!) in it, so I'll need to clean that up every hour or so. There are a couple of other minor things which I'll need to fix before I push it live again, so for now the bot is offline. Thanks for bringing this up.
